"""Deterministic artifact-backed recommendation primitives."""

from gamelens_recommender.artifacts import ArtifactError, LoadedArtifact, load_artifact
from gamelens_recommender.collaborative import (
    COLLABORATIVE_SCORING_CONFIG,
    CollaborativeCandidateScore,
    CollaborativeQueryContext,
    CollaborativeQuerySource,
    CollaborativeScorer,
    CollaborativeScoringConfig,
    CollaborativeScoringDiagnostics,
    CollaborativeScoringError,
    CollaborativeScoringIdentity,
    CollaborativeScoringResult,
    CollaborativeSourceEdge,
    CollaborativeSourceState,
    canonicalize_collaborative_query_sources,
)
from gamelens_recommender.collaborative_artifacts import (
    CollaborativeArtifactError,
    CollaborativeBuildMetadata,
    LoadedCollaborativeArtifact,
    build_collaborative_artifact,
    inspect_collaborative_artifact,
    load_collaborative_artifact,
)
from gamelens_recommender.collaborative_training import (
    BinaryInteractionMatrix,
    CollaborativeNeighborhoods,
    CollaborativeTrainingError,
    build_binary_interaction_matrix,
    fit_collaborative_neighborhoods,
    fit_item_item_cosine,
    quantize_similarity,
    validate_binary_interaction_matrix,
    validate_collaborative_neighborhoods,
)
from gamelens_recommender.feedback import (
    FEEDBACK_POLICY_CONFIG,
    AffinityCandidateScore,
    AffinityMaterializationError,
    AffinityMaterializationResult,
    FeedbackPolicyConfig,
    FeedbackRanker,
    PreparedFeedbackRankingContext,
)
from gamelens_recommender.interaction_snapshot import (
    LABEL_POLICY_ID,
    SnapshotAuditError,
    SupportedProfiles,
    audit_fixture,
    audit_profiles,
    canonicalize_profiles,
    profile_fingerprint,
    prune_supported_profiles,
)
from gamelens_recommender.ranking import (
    BaseCandidateMaterializationError,
    ContentRanker,
    InsufficientContextError,
)
from gamelens_recommender.schemas import (
    ActiveGameFeedback,
    BaseCandidateScore,
    CatalogItem,
    CatalogSnapshot,
    FeedbackPolicyIdentity,
    PersonalizedRankingResult,
    PersonalizedRecommendation,
    PositiveFeedbackSource,
    TaxonomyValue,
    UserContext,
    canonical_snapshot,
)
from gamelens_recommender.training import build_artifact

__all__ = [
    "ActiveGameFeedback",
    "AffinityCandidateScore",
    "AffinityMaterializationError",
    "AffinityMaterializationResult",
    "ArtifactError",
    "BaseCandidateScore",
    "BaseCandidateMaterializationError",
    "BinaryInteractionMatrix",
    "COLLABORATIVE_SCORING_CONFIG",
    "CatalogItem",
    "CatalogSnapshot",
    "CollaborativeArtifactError",
    "CollaborativeBuildMetadata",
    "CollaborativeCandidateScore",
    "CollaborativeNeighborhoods",
    "CollaborativeQueryContext",
    "CollaborativeQuerySource",
    "CollaborativeScorer",
    "CollaborativeScoringConfig",
    "CollaborativeScoringDiagnostics",
    "CollaborativeScoringError",
    "CollaborativeScoringIdentity",
    "CollaborativeScoringResult",
    "CollaborativeSourceEdge",
    "CollaborativeSourceState",
    "CollaborativeTrainingError",
    "ContentRanker",
    "FEEDBACK_POLICY_CONFIG",
    "LABEL_POLICY_ID",
    "FeedbackPolicyConfig",
    "FeedbackPolicyIdentity",
    "FeedbackRanker",
    "InsufficientContextError",
    "LoadedArtifact",
    "LoadedCollaborativeArtifact",
    "PersonalizedRankingResult",
    "PersonalizedRecommendation",
    "PositiveFeedbackSource",
    "PreparedFeedbackRankingContext",
    "SnapshotAuditError",
    "SupportedProfiles",
    "TaxonomyValue",
    "UserContext",
    "audit_fixture",
    "audit_profiles",
    "build_artifact",
    "build_binary_interaction_matrix",
    "build_collaborative_artifact",
    "canonical_snapshot",
    "canonicalize_collaborative_query_sources",
    "load_artifact",
    "load_collaborative_artifact",
    "fit_collaborative_neighborhoods",
    "fit_item_item_cosine",
    "inspect_collaborative_artifact",
    "canonicalize_profiles",
    "profile_fingerprint",
    "prune_supported_profiles",
    "quantize_similarity",
    "validate_binary_interaction_matrix",
    "validate_collaborative_neighborhoods",
]

__version__ = "0.1.0"
