/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report application health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter catalog games */
        get: operations["list_games_api_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one catalog game */
        get: operations["get_game_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Genres */
        get: operations["list_genres_api_v1_metadata_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_v1_metadata_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_v1_metadata_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report recommendation model readiness */
        get: operations["model_status_api_v1_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend games from anonymous request-scoped preferences */
        post: operations["create_recommendations_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveModel */
        ActiveModel: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Artifact Schema */
            artifact_schema?: string | null;
            /** Data Fingerprint */
            data_fingerprint?: string | null;
        };
        /**
         * CatalogSort
         * @enum {string}
         */
        CatalogSort: "popularity" | "rating" | "release_date" | "title";
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvidenceValue */
        EvidenceValue: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Release Date */
            release_date: string | null;
            /** Developer */
            developer: string | null;
            /** Publisher */
            publisher: string | null;
            /** Average Rating */
            average_rating: number | null;
            /** Rating Count */
            rating_count: number;
            /** Popularity Score */
            popularity_score: number;
            /** Genres */
            genres: components["schemas"]["TaxonomyItem"][];
            /** Tags */
            tags: components["schemas"]["TaxonomyItem"][];
            /** Platforms */
            platforms: components["schemas"]["TaxonomyItem"][];
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GamePage */
        GamePage: {
            /** Items */
            items: components["schemas"]["GameSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Release Date */
            release_date: string | null;
            /** Developer */
            developer: string | null;
            /** Publisher */
            publisher: string | null;
            /** Average Rating */
            average_rating: number | null;
            /** Rating Count */
            rating_count: number;
            /** Popularity Score */
            popularity_score: number;
            /** Genres */
            genres: components["schemas"]["TaxonomyItem"][];
            /** Tags */
            tags: components["schemas"]["TaxonomyItem"][];
            /** Platforms */
            platforms: components["schemas"]["TaxonomyItem"][];
            /** Cover Image Url */
            cover_image_url: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Service */
            service: string;
            /** Environment */
            environment: string;
            /**
             * Database
             * @enum {string}
             */
            database: "ready" | "unavailable";
        };
        /** ModelCapabilities */
        ModelCapabilities: {
            /** Recommend */
            recommend: boolean;
            /** Explanations */
            explanations: boolean;
        };
        /** ModelStatusResponse */
        ModelStatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_configured" | "unavailable";
            active_model: components["schemas"]["ActiveModel"] | null;
            capabilities: components["schemas"]["ModelCapabilities"];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
            /** Feature Families */
            feature_families?: string[] | null;
        };
        /** RecommendationEvidenceResponse */
        RecommendationEvidenceResponse: {
            /** Matching Genres */
            matching_genres: components["schemas"]["EvidenceValue"][];
            /** Matching Tags */
            matching_tags: components["schemas"]["EvidenceValue"][];
            /** Preferred Platforms */
            preferred_platforms: components["schemas"]["EvidenceValue"][];
            /** Similar Selected Games */
            similar_selected_games: components["schemas"]["SimilarSelectedGameResponse"][];
            /** Popularity Score */
            popularity_score: number;
        };
        /** RecommendationExplanationResponse */
        RecommendationExplanationResponse: {
            /** Summary */
            summary: string;
            /** Reasons */
            reasons: string[];
        };
        /** RecommendationItemResponse */
        RecommendationItemResponse: {
            /** Rank */
            rank: number;
            /** Ranking Score */
            ranking_score: number;
            game: components["schemas"]["GameSummary"];
            /** Components */
            components: components["schemas"]["ScoreComponentResponse"][];
            evidence: components["schemas"]["RecommendationEvidenceResponse"];
            explanation: components["schemas"]["RecommendationExplanationResponse"];
        };
        /** RecommendationModelIdentity */
        RecommendationModelIdentity: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Data Fingerprint */
            data_fingerprint: string;
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Selected Game Ids */
            selected_game_ids?: number[];
            /** Preferred Genres */
            preferred_genres?: string[];
            /** Preferred Tags */
            preferred_tags?: string[];
            /** Preferred Platforms */
            preferred_platforms?: string[];
            /**
             * Top K
             * @default 10
             */
            top_k?: number;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            model: components["schemas"]["RecommendationModelIdentity"];
            /**
             * Response Reason
             * @enum {string}
             */
            response_reason: "recommendations" | "no_content_support";
            /** Requested Top K */
            requested_top_k: number;
            /** Items */
            items: components["schemas"]["RecommendationItemResponse"][];
        };
        /** ScoreComponentResponse */
        ScoreComponentResponse: {
            /**
             * Name
             * @enum {string}
             */
            name: "content" | "platform" | "popularity";
            /** Raw Score */
            raw_score: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
        };
        /** SimilarSelectedGameResponse */
        SimilarSelectedGameResponse: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Similarity Score */
            similarity_score: number;
        };
        /** TaxonomyItem */
        TaxonomyItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database or required schema is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_games_api_v1_games_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                q?: string | null;
                genre?: string | null;
                tag?: string | null;
                platform?: string | null;
                sort?: components["schemas"]["CatalogSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePage"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_game_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_genres_api_v1_metadata_genres_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyItem"][];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tags_api_v1_metadata_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyItem"][];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_platforms_api_v1_metadata_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyItem"][];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    model_status_api_v1_models_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_recommendations_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Recommendation request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The recommendation model or database is temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
